# Generated by Django 5.1.4 on 2025-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_url',
            field=models.URLField(blank=True, help_text='External registration link (if not using built-in registration)', max_length=500),
        ),
        migrations.AddField(
            model_name='tournament',
            name='website_url',
            field=models.URLField(blank=True, help_text='Tournament website or information page', max_length=500),
        ),
    ]
