# Generated by Django 5.1.4 on 2025-12-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_registration_url_tournament_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.CharField(blank=True, help_text="Pool/Group assignment (e.g., 'A', 'B', 'C', 'D')", max_length=10),
        ),
    ]
