# Generated by Django 5.1.4 on 2025-12-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='seed',
        ),
    ]
