# Generated by Django 5.1.4 on 2025-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_team_options_remove_team_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.CharField(blank=True, help_text='Pool this game belongs to', max_length=10),
        ),
    ]
