EVENT_GAME_STARTED = "game.started"
EVENT_GAME_COMPLETED = "game.completed"
EVENT_CURSOR_PAIR_INDEX_SET = "cursor.pair_index_set"
EVENT_ATTEMPT_RECORDED = "attempt.recorded"
EVENT_ATTEMPTS_QUESTION_CLEARED = "attempts.question_cleared"
EVENT_BONUS_RESULT_SET = "bonus.result_set"
EVENT_MARKER_SET = "marker.set"
EVENT_MARKER_REMOVED = "marker.removed"
EVENT_LINEUP_SET = "lineup.set"
EVENT_LINEUP_REMOVED = "lineup.removed"

EVENT_TYPES = {
    EVENT_GAME_STARTED,
    EVENT_GAME_COMPLETED,
    EVENT_CURSOR_PAIR_INDEX_SET,
    EVENT_ATTEMPT_RECORDED,
    EVENT_ATTEMPTS_QUESTION_CLEARED,
    EVENT_BONUS_RESULT_SET,
    EVENT_MARKER_SET,
    EVENT_MARKER_REMOVED,
    EVENT_LINEUP_SET,
    EVENT_LINEUP_REMOVED,
}
