# Generated by Django 5.1.4 on 2025-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('BIOLOGY', 'Biology'), ('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('EARTH_SPACE', 'Earth and Space'), ('MATH', 'Math'), ('ENERGY', 'Energy')], db_index=True, max_length=20)),
                ('question_type', models.CharField(choices=[('SHORT_ANSWER', 'Short Answer'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('IDENTIFY_ALL', 'Identify All'), ('RANK', 'Rank')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10)),
                ('correct_answer', models.TextField(help_text='The correct answer(s)')),
                ('choice_w', models.CharField(blank=True, max_length=500, null=True)),
                ('choice_x', models.CharField(blank=True, max_length=500, null=True)),
                ('choice_y', models.CharField(blank=True, max_length=500, null=True)),
                ('choice_z', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, help_text="Source of question (e.g., 'NSB 2023 Regionals')", max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the answer', null=True)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_question_history',
                'ordering': ['-answered_at'],
            },
        ),
    ]
