# Generated by Django 5.1.4 on 2025-12-16 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'question_type'], name='questions_categor_5233c4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='questions.question'),
        ),
        migrations.AddField(
            model_name='userquestionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='questions.question'),
        ),
        migrations.AddField(
            model_name='userquestionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'question')},
        ),
        migrations.AddIndex(
            model_name='userquestionhistory',
            index=models.Index(fields=['user', 'answered_at'], name='user_questi_user_id_fd4cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionhistory',
            index=models.Index(fields=['question', 'is_correct'], name='user_questi_questio_ea9eb2_idx'),
        ),
    ]
