# Generated by Django 5.1.4 on 2025-12-17 03:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_difficu_8150ad_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NSB_REGIONALS', 'NSB Regionals'), ('NSB_NATIONALS', 'NSB Nationals'), ('PRACTICE_SET', 'Practice Set'), ('CUSTOM', 'Custom')], max_length=50), blank=True, default=list, help_text='Sources of question (can select multiple)', size=None),
        ),
    ]
