# Generated by Django 5.1.4 on 2025-12-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_difficu_8150ad_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, help_text='Source of question', max_length=50, null=True),
        ),
    ]
