# Generated by Django 5.1.4 on 2025-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_questions_difficu_8150ad_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice_w',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_x',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_y',
            new_name='option_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_z',
            new_name='option_4',
        ),
    ]
