# Generated by Django 5.1.4 on 2025-12-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_choices_to_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, choices=[('MIT_2025', 'MIT 2025'), ('USER_SUBMITTED', 'User Submitted')], help_text='Source of question', max_length=50, null=True),
        ),
    ]
