# Generated by Django 5.1.4 on 2025-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_change_source_to_single_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='The correct answer(s)', max_length=1000),
        ),
    ]
