# Generated by Django 5.1.4 on 2025-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_change_correct_answer_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_style',
            field=models.CharField(choices=[('SHORT_ANSWER', 'Short Answer'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('IDENTIFY_ALL', 'Identify All'), ('RANK', 'Rank')], db_index=True, default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TOSSUP', 'Tossup'), ('BONUS', 'Bonus')], db_index=True, default='TOSSUP', max_length=20),
        ),
    ]
