# Generated by Django 5.1.4 on 2025-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_question_style_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('BIOLOGY', 'Biology'), ('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('EARTH_SPACE', 'Earth and Space'), ('MATH', 'Math'), ('ENERGY', 'Energy'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(blank=True, help_text='Option W', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(blank=True, help_text='Option X', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, help_text='Option Y', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, help_text='Option Z', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, choices=[('MIT_2025', 'MIT 2025'), ('REGIONALS_2023', 'Regionals 2023'), ('REGIONALS_2024', 'Regionals 2024'), ('REGIONALS_2025', 'Regionals 2025'), ('NATIONALS_2023', 'Nationals 2023'), ('NATIONALS_2024', 'Nationals 2024'), ('NATIONALS_2025', 'Nationals 2025'), ('INVITATIONAL', 'Invitational'), ('USER_SUBMITTED', 'User Submitted')], help_text='Source of question', max_length=50, null=True),
        ),
    ]
