# Generated by Django 5.1.4 on 2026-03-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0004_remove_fact_rollups'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameplayerlineupsegment',
            new_name='moss_gamepl_game_id_cf4b01_idx',
            old_name='moss_gamepl_game_id_f710ce_idx',
        ),
        migrations.RenameIndex(
            model_name='gameplayerlineupsegment',
            new_name='moss_gamepl_game_id_f1fe6f_idx',
            old_name='moss_gamepl_game_id_e648e6_idx',
        ),
        migrations.RenameIndex(
            model_name='gameteamquestionoutcome',
            new_name='moss_gamete_game_id_adab37_idx',
            old_name='moss_gamete_game_id_d1134f_idx',
        ),
        migrations.RenameIndex(
            model_name='gameteamquestionoutcome',
            new_name='moss_gamete_packet__c2ad7b_idx',
            old_name='moss_gamete_packet__10db77_idx',
        ),
        migrations.RenameIndex(
            model_name='packetquestion',
            new_name='moss_packet_packet__ebedf6_idx',
            old_name='moss_packetq_packet__0aa0ee_idx',
        ),
        migrations.RenameIndex(
            model_name='packetquestion',
            new_name='moss_packet_packet__f4a17e_idx',
            old_name='moss_packetq_packet__5be45c_idx',
        ),
    ]
